# Generated by Django 6.0.4 on 2026-05-01 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Problem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Enter your name ', max_length=100)),
                ('email', models.EmailField(help_text='Enter your valid email ', max_length=254)),
                ('contact', models.CharField(help_text='Enter your 10 digits phone number', max_length=10)),
                ('message', models.TextField(help_text='Enter about the problem you faced')),
            ],
        ),
    ]
