# Generated by Django 6.0.4 on 2026-05-01 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Myapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cab',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Enter your name ', max_length=100)),
                ('email', models.EmailField(help_text='Enter your valid email ', max_length=254)),
                ('contact', models.CharField(help_text='Enter your 10 digits phone number', max_length=10)),
                ('pickup', models.CharField(help_text='Enter your Pickup loaction', max_length=1000)),
                ('drop', models.CharField(help_text='Enter your Drop loaction', max_length=1000)),
                ('passenger', models.CharField(help_text='Enter your No of Passenger', max_length=10)),
                ('luggage', models.CharField(help_text='Enter luggage you carry', max_length=8)),
            ],
        ),
    ]
