# Generated by Django 6.0.4 on 2026-05-01 19:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Myapp', '0003_hotel'),
    ]

    operations = [
        migrations.RenameField(
            model_name='hotel',
            old_name='luggage',
            new_name='checkin',
        ),
    ]
