# Generated by Django 6.0.4 on 2026-05-01 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Myapp', '0004_rename_luggage_hotel_checkin'),
    ]

    operations = [
        migrations.CreateModel(
            name='Adventure',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Enter your name ', max_length=100)),
                ('email', models.EmailField(help_text='Enter your valid email ', max_length=254)),
                ('contact', models.CharField(help_text='Enter your 10 digits phone number', max_length=10)),
                ('emergency', models.CharField(help_text='Enter 10 digits  emergency phone number', max_length=10)),
                ('location', models.CharField(help_text='Enter 10 digits  emergency phone number', max_length=50)),
                ('date', models.DateField()),
                ('person', models.CharField(help_text='Enter your No of person', max_length=10)),
                ('experience', models.CharField(help_text='Enter your Experience level', max_length=10)),
            ],
        ),
    ]
