# Generated by Django 6.0.4 on 2026-05-01 20:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Myapp', '0005_adventure'),
    ]

    operations = [
        migrations.CreateModel(
            name='Custom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Enter your name ', max_length=100)),
                ('email', models.EmailField(help_text='Enter your valid email ', max_length=254)),
                ('contact', models.CharField(help_text='Enter your 10 digits phone number', max_length=10)),
                ('emergency', models.CharField(help_text='Enter 10 digits  emergency phone number', max_length=10)),
                ('location', models.CharField(help_text='Enter the prefered location', max_length=50)),
                ('date', models.DateField()),
                ('person', models.CharField(help_text='Enter your No of person', max_length=10)),
                ('destination', models.CharField(help_text='Enter your choice', max_length=10)),
                ('budget', models.CharField(help_text='Enter your budget', max_length=10)),
                ('travel', models.CharField(help_text='Enter your travel prefrence ', max_length=100)),
                ('activities', models.CharField(help_text='Enter your choice', max_length=10)),
            ],
        ),
        migrations.AlterField(
            model_name='adventure',
            name='location',
            field=models.CharField(help_text='Enter the prefered location', max_length=50),
        ),
    ]
